//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/FastAndFractured/Player/Input/PlayerInputMap.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputAction: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputAction()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputMap"",
    ""maps"": [
        {
            ""name"": ""PlayerInputActions"",
            ""id"": ""edf5a5d7-9735-415d-9f5e-d15529fc080f"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""Value"",
                    ""id"": ""017e8e69-ccd5-4d28-b82c-187068865d4f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Accelerate"",
                    ""type"": ""Value"",
                    ""id"": ""2f11717d-ef60-4557-bdaa-c65a52510283"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Reverse"",
                    ""type"": ""Value"",
                    ""id"": ""38a23e7d-4f3d-4eda-bf26-222fccc54458"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Brake"",
                    ""type"": ""Button"",
                    ""id"": ""07d77117-403b-42b2-a522-b8aeac24abbc"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ShootingMode"",
                    ""type"": ""Button"",
                    ""id"": ""df5a71de-dd17-4098-8f91-0ae3a2194ab2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraMove"",
                    ""type"": ""Value"",
                    ""id"": ""a8e50b16-4e0f-41f4-8335-eb73eb98a9cc"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraMoveMouse"",
                    ""type"": ""Value"",
                    ""id"": ""09b600ea-96de-494f-b44a-dc12c9db3d30"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""2c14d8bd-8915-44fd-8137-042f895d90b5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SpecialAbility"",
                    ""type"": ""Button"",
                    ""id"": ""317d9c30-4111-454d-bca9-944956da53b0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ResetCamera"",
                    ""type"": ""Button"",
                    ""id"": ""74663605-a100-4f00-b64f-a4c09a5a6e51"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ThrowMine"",
                    ""type"": ""Button"",
                    ""id"": ""883574eb-b2c2-4a12-bd55-bd2b3ba5b2b1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""834648fa-4de3-4589-bd1f-f58b7313a071"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dash"",
                    ""type"": ""Button"",
                    ""id"": ""382fdf1f-f53c-45a5-8c08-1aac93b6e9e3"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugAIChangeState"",
                    ""type"": ""Button"",
                    ""id"": ""c7948b44-ab46-4ca0-8db2-ff3bf4abe4d5"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugAIResetPosition"",
                    ""type"": ""Button"",
                    ""id"": ""6cff68b6-f007-416e-bcfa-1fa0a926af41"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugRemoveUltimateAbilityCooldown"",
                    ""type"": ""Button"",
                    ""id"": ""909adfcd-465a-471b-a7b7-80d412a8ccda"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""MovementInputsKeyboard"",
                    ""id"": ""dc0194d3-a528-4d67-9bf7-2acb29e47454"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""922dbe64-ba9e-4a83-bc7d-7a53b4377f18"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""ca149963-95f1-4f2f-9645-78770e569893"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""65560150-4fd8-45dd-b965-13baa8f3cd83"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""57c52d35-d41c-4709-8264-bfb9a24fc834"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""b5be16e8-6bf7-4898-8da3-e92391a9f8fc"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""328e211d-b69b-4e70-b709-e6baecb5ce08"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reverse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19b9bf36-3508-483a-b995-925ff984817f"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e314cba-3b6d-48d2-a37c-5933bd4bc3ea"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Brake"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""406dea28-aafa-44ce-8e1f-54249e513c07"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootingMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c29a6517-5e5e-4bfe-bbf8-1c3669ccf9f7"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ShootingMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""08273a87-ad1d-43ea-84eb-283b1aed8ac2"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b4525a62-2fa9-456d-9156-af301c7b905c"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CameraMoveMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8330e2c9-65e8-4dbb-a1dc-6694eefeac60"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b408e85-b686-48f5-8201-fb1966f6901e"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""93826a7f-94ea-4b11-9fdb-b947c796abdb"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpecialAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2b3f009-c78f-4813-9c68-ac914224ba7e"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SpecialAbility"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3adb6dd7-a8c9-43f3-bc74-7c6df39ca767"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c7fa6697-e8f6-419e-b130-a260d20b5c1d"",
                    ""path"": ""<Keyboard>/g"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetCamera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c187e97-d67f-4e4f-90d2-3b8e4ac8f506"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowMine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4a63d8d-ad1e-43c8-b1cb-075b326f2867"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ThrowMine"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1446f26c-74cc-4344-a2a0-3aa92e466d4f"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Accelerate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f05ea924-4f10-44ae-b542-f939064a169a"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c3a8a94d-374c-4160-8a63-d67e0a83c64b"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""30fe1010-b9d7-4840-8fbc-6454373cb051"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b8dd7fcd-cee9-4b84-a153-f5dbf7165f3d"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dash"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8ded8af-b478-41fe-b47d-4a1371bd43be"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugAIChangeState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""edc1bed8-d6d1-4c51-b2d2-d576811dfeac"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugAIResetPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""18becf51-2637-4d85-827f-69f182904120"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugRemoveUltimateAbilityCooldown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""MenuInputActions"",
            ""id"": ""5cd8f628-2a28-4b94-8e1d-cb1598bd9e4b"",
            ""actions"": [
                {
                    ""name"": ""GoBack"",
                    ""type"": ""Button"",
                    ""id"": ""6da1b141-dd57-452c-a565-a440677ea960"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftDirection"",
                    ""type"": ""Button"",
                    ""id"": ""7be6982e-b3c7-4924-8a79-c826534abe31"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightDirection"",
                    ""type"": ""Button"",
                    ""id"": ""a6e5a43e-9511-4eae-835c-81da6c831297"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UpDirection"",
                    ""type"": ""Button"",
                    ""id"": ""56310f66-7493-403c-94ad-6290033f41dd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DownDirection"",
                    ""type"": ""Button"",
                    ""id"": ""1fda791f-4c80-45e5-8352-428f77afda65"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftCharacter"",
                    ""type"": ""Button"",
                    ""id"": ""8b0383a8-6359-4d59-89ab-0de70f93cd8c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightCharacter"",
                    ""type"": ""Button"",
                    ""id"": ""d3fc899d-9d86-43ad-89e4-ac4ff6399035"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftSkin"",
                    ""type"": ""Button"",
                    ""id"": ""4219722f-c485-4e89-ae8e-f7b0438b36c2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightSkin"",
                    ""type"": ""Button"",
                    ""id"": ""35e86643-f04e-498b-98b2-0f8363742ebd"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartGame"",
                    ""type"": ""Button"",
                    ""id"": ""7333155d-fca4-4b9a-90ce-651cb225ccde"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DebugUnlockSkins"",
                    ""type"": ""Button"",
                    ""id"": ""3023a69b-e852-4400-9968-35c232da33c8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ad7ea959-e90f-4cb8-8fef-592c48f58c15"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2164c23c-ec01-4d6a-b1c1-e5f245223429"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""GoBack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3e8096f5-e15a-49fa-b8f1-0272f1e3a9ac"",
                    ""path"": ""<Gamepad>/leftStick/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftDirection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f98998cb-b8b9-42f8-a323-2cea6d38bae7"",
                    ""path"": ""<Gamepad>/leftStick/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightDirection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9de16999-0a0a-4bc7-b1e8-667d006b1a23"",
                    ""path"": ""<Gamepad>/leftStick/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpDirection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""180fc230-29ee-42f9-9d23-880b70c529e4"",
                    ""path"": ""<Gamepad>/leftStick/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DownDirection"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1741046-fda7-43da-ad12-07fdf3680267"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4880748b-afa7-4fe7-a87a-f4778fedad65"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightCharacter"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7cd48dd-8f6e-441a-bab7-8d3b650b50bc"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftSkin"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1369c782-01f0-4f4f-a784-ece3c5f1c26b"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightSkin"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0d9d0fc8-9771-4d06-8e5c-1926098b48f8"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9a28c38e-20f5-4e43-8c3f-81f8c020b8d3"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DebugUnlockSkins"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerInputActions
        m_PlayerInputActions = asset.FindActionMap("PlayerInputActions", throwIfNotFound: true);
        m_PlayerInputActions_Movement = m_PlayerInputActions.FindAction("Movement", throwIfNotFound: true);
        m_PlayerInputActions_Accelerate = m_PlayerInputActions.FindAction("Accelerate", throwIfNotFound: true);
        m_PlayerInputActions_Reverse = m_PlayerInputActions.FindAction("Reverse", throwIfNotFound: true);
        m_PlayerInputActions_Brake = m_PlayerInputActions.FindAction("Brake", throwIfNotFound: true);
        m_PlayerInputActions_ShootingMode = m_PlayerInputActions.FindAction("ShootingMode", throwIfNotFound: true);
        m_PlayerInputActions_CameraMove = m_PlayerInputActions.FindAction("CameraMove", throwIfNotFound: true);
        m_PlayerInputActions_CameraMoveMouse = m_PlayerInputActions.FindAction("CameraMoveMouse", throwIfNotFound: true);
        m_PlayerInputActions_Shoot = m_PlayerInputActions.FindAction("Shoot", throwIfNotFound: true);
        m_PlayerInputActions_SpecialAbility = m_PlayerInputActions.FindAction("SpecialAbility", throwIfNotFound: true);
        m_PlayerInputActions_ResetCamera = m_PlayerInputActions.FindAction("ResetCamera", throwIfNotFound: true);
        m_PlayerInputActions_ThrowMine = m_PlayerInputActions.FindAction("ThrowMine", throwIfNotFound: true);
        m_PlayerInputActions_Pause = m_PlayerInputActions.FindAction("Pause", throwIfNotFound: true);
        m_PlayerInputActions_Dash = m_PlayerInputActions.FindAction("Dash", throwIfNotFound: true);
        m_PlayerInputActions_DebugAIChangeState = m_PlayerInputActions.FindAction("DebugAIChangeState", throwIfNotFound: true);
        m_PlayerInputActions_DebugAIResetPosition = m_PlayerInputActions.FindAction("DebugAIResetPosition", throwIfNotFound: true);
        m_PlayerInputActions_DebugRemoveUltimateAbilityCooldown = m_PlayerInputActions.FindAction("DebugRemoveUltimateAbilityCooldown", throwIfNotFound: true);
        // MenuInputActions
        m_MenuInputActions = asset.FindActionMap("MenuInputActions", throwIfNotFound: true);
        m_MenuInputActions_GoBack = m_MenuInputActions.FindAction("GoBack", throwIfNotFound: true);
        m_MenuInputActions_LeftDirection = m_MenuInputActions.FindAction("LeftDirection", throwIfNotFound: true);
        m_MenuInputActions_RightDirection = m_MenuInputActions.FindAction("RightDirection", throwIfNotFound: true);
        m_MenuInputActions_UpDirection = m_MenuInputActions.FindAction("UpDirection", throwIfNotFound: true);
        m_MenuInputActions_DownDirection = m_MenuInputActions.FindAction("DownDirection", throwIfNotFound: true);
        m_MenuInputActions_LeftCharacter = m_MenuInputActions.FindAction("LeftCharacter", throwIfNotFound: true);
        m_MenuInputActions_RightCharacter = m_MenuInputActions.FindAction("RightCharacter", throwIfNotFound: true);
        m_MenuInputActions_LeftSkin = m_MenuInputActions.FindAction("LeftSkin", throwIfNotFound: true);
        m_MenuInputActions_RightSkin = m_MenuInputActions.FindAction("RightSkin", throwIfNotFound: true);
        m_MenuInputActions_StartGame = m_MenuInputActions.FindAction("StartGame", throwIfNotFound: true);
        m_MenuInputActions_DebugUnlockSkins = m_MenuInputActions.FindAction("DebugUnlockSkins", throwIfNotFound: true);
    }

    ~@PlayerInputAction()
    {
        UnityEngine.Debug.Assert(!m_PlayerInputActions.enabled, "This will cause a leak and performance issues, PlayerInputAction.PlayerInputActions.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_MenuInputActions.enabled, "This will cause a leak and performance issues, PlayerInputAction.MenuInputActions.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInputActions
    private readonly InputActionMap m_PlayerInputActions;
    private List<IPlayerInputActionsActions> m_PlayerInputActionsActionsCallbackInterfaces = new List<IPlayerInputActionsActions>();
    private readonly InputAction m_PlayerInputActions_Movement;
    private readonly InputAction m_PlayerInputActions_Accelerate;
    private readonly InputAction m_PlayerInputActions_Reverse;
    private readonly InputAction m_PlayerInputActions_Brake;
    private readonly InputAction m_PlayerInputActions_ShootingMode;
    private readonly InputAction m_PlayerInputActions_CameraMove;
    private readonly InputAction m_PlayerInputActions_CameraMoveMouse;
    private readonly InputAction m_PlayerInputActions_Shoot;
    private readonly InputAction m_PlayerInputActions_SpecialAbility;
    private readonly InputAction m_PlayerInputActions_ResetCamera;
    private readonly InputAction m_PlayerInputActions_ThrowMine;
    private readonly InputAction m_PlayerInputActions_Pause;
    private readonly InputAction m_PlayerInputActions_Dash;
    private readonly InputAction m_PlayerInputActions_DebugAIChangeState;
    private readonly InputAction m_PlayerInputActions_DebugAIResetPosition;
    private readonly InputAction m_PlayerInputActions_DebugRemoveUltimateAbilityCooldown;
    public struct PlayerInputActionsActions
    {
        private @PlayerInputAction m_Wrapper;
        public PlayerInputActionsActions(@PlayerInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_PlayerInputActions_Movement;
        public InputAction @Accelerate => m_Wrapper.m_PlayerInputActions_Accelerate;
        public InputAction @Reverse => m_Wrapper.m_PlayerInputActions_Reverse;
        public InputAction @Brake => m_Wrapper.m_PlayerInputActions_Brake;
        public InputAction @ShootingMode => m_Wrapper.m_PlayerInputActions_ShootingMode;
        public InputAction @CameraMove => m_Wrapper.m_PlayerInputActions_CameraMove;
        public InputAction @CameraMoveMouse => m_Wrapper.m_PlayerInputActions_CameraMoveMouse;
        public InputAction @Shoot => m_Wrapper.m_PlayerInputActions_Shoot;
        public InputAction @SpecialAbility => m_Wrapper.m_PlayerInputActions_SpecialAbility;
        public InputAction @ResetCamera => m_Wrapper.m_PlayerInputActions_ResetCamera;
        public InputAction @ThrowMine => m_Wrapper.m_PlayerInputActions_ThrowMine;
        public InputAction @Pause => m_Wrapper.m_PlayerInputActions_Pause;
        public InputAction @Dash => m_Wrapper.m_PlayerInputActions_Dash;
        public InputAction @DebugAIChangeState => m_Wrapper.m_PlayerInputActions_DebugAIChangeState;
        public InputAction @DebugAIResetPosition => m_Wrapper.m_PlayerInputActions_DebugAIResetPosition;
        public InputAction @DebugRemoveUltimateAbilityCooldown => m_Wrapper.m_PlayerInputActions_DebugRemoveUltimateAbilityCooldown;
        public InputActionMap Get() { return m_Wrapper.m_PlayerInputActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerInputActionsActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerInputActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerInputActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerInputActionsActionsCallbackInterfaces.Add(instance);
            @Movement.started += instance.OnMovement;
            @Movement.performed += instance.OnMovement;
            @Movement.canceled += instance.OnMovement;
            @Accelerate.started += instance.OnAccelerate;
            @Accelerate.performed += instance.OnAccelerate;
            @Accelerate.canceled += instance.OnAccelerate;
            @Reverse.started += instance.OnReverse;
            @Reverse.performed += instance.OnReverse;
            @Reverse.canceled += instance.OnReverse;
            @Brake.started += instance.OnBrake;
            @Brake.performed += instance.OnBrake;
            @Brake.canceled += instance.OnBrake;
            @ShootingMode.started += instance.OnShootingMode;
            @ShootingMode.performed += instance.OnShootingMode;
            @ShootingMode.canceled += instance.OnShootingMode;
            @CameraMove.started += instance.OnCameraMove;
            @CameraMove.performed += instance.OnCameraMove;
            @CameraMove.canceled += instance.OnCameraMove;
            @CameraMoveMouse.started += instance.OnCameraMoveMouse;
            @CameraMoveMouse.performed += instance.OnCameraMoveMouse;
            @CameraMoveMouse.canceled += instance.OnCameraMoveMouse;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @SpecialAbility.started += instance.OnSpecialAbility;
            @SpecialAbility.performed += instance.OnSpecialAbility;
            @SpecialAbility.canceled += instance.OnSpecialAbility;
            @ResetCamera.started += instance.OnResetCamera;
            @ResetCamera.performed += instance.OnResetCamera;
            @ResetCamera.canceled += instance.OnResetCamera;
            @ThrowMine.started += instance.OnThrowMine;
            @ThrowMine.performed += instance.OnThrowMine;
            @ThrowMine.canceled += instance.OnThrowMine;
            @Pause.started += instance.OnPause;
            @Pause.performed += instance.OnPause;
            @Pause.canceled += instance.OnPause;
            @Dash.started += instance.OnDash;
            @Dash.performed += instance.OnDash;
            @Dash.canceled += instance.OnDash;
            @DebugAIChangeState.started += instance.OnDebugAIChangeState;
            @DebugAIChangeState.performed += instance.OnDebugAIChangeState;
            @DebugAIChangeState.canceled += instance.OnDebugAIChangeState;
            @DebugAIResetPosition.started += instance.OnDebugAIResetPosition;
            @DebugAIResetPosition.performed += instance.OnDebugAIResetPosition;
            @DebugAIResetPosition.canceled += instance.OnDebugAIResetPosition;
            @DebugRemoveUltimateAbilityCooldown.started += instance.OnDebugRemoveUltimateAbilityCooldown;
            @DebugRemoveUltimateAbilityCooldown.performed += instance.OnDebugRemoveUltimateAbilityCooldown;
            @DebugRemoveUltimateAbilityCooldown.canceled += instance.OnDebugRemoveUltimateAbilityCooldown;
        }

        private void UnregisterCallbacks(IPlayerInputActionsActions instance)
        {
            @Movement.started -= instance.OnMovement;
            @Movement.performed -= instance.OnMovement;
            @Movement.canceled -= instance.OnMovement;
            @Accelerate.started -= instance.OnAccelerate;
            @Accelerate.performed -= instance.OnAccelerate;
            @Accelerate.canceled -= instance.OnAccelerate;
            @Reverse.started -= instance.OnReverse;
            @Reverse.performed -= instance.OnReverse;
            @Reverse.canceled -= instance.OnReverse;
            @Brake.started -= instance.OnBrake;
            @Brake.performed -= instance.OnBrake;
            @Brake.canceled -= instance.OnBrake;
            @ShootingMode.started -= instance.OnShootingMode;
            @ShootingMode.performed -= instance.OnShootingMode;
            @ShootingMode.canceled -= instance.OnShootingMode;
            @CameraMove.started -= instance.OnCameraMove;
            @CameraMove.performed -= instance.OnCameraMove;
            @CameraMove.canceled -= instance.OnCameraMove;
            @CameraMoveMouse.started -= instance.OnCameraMoveMouse;
            @CameraMoveMouse.performed -= instance.OnCameraMoveMouse;
            @CameraMoveMouse.canceled -= instance.OnCameraMoveMouse;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @SpecialAbility.started -= instance.OnSpecialAbility;
            @SpecialAbility.performed -= instance.OnSpecialAbility;
            @SpecialAbility.canceled -= instance.OnSpecialAbility;
            @ResetCamera.started -= instance.OnResetCamera;
            @ResetCamera.performed -= instance.OnResetCamera;
            @ResetCamera.canceled -= instance.OnResetCamera;
            @ThrowMine.started -= instance.OnThrowMine;
            @ThrowMine.performed -= instance.OnThrowMine;
            @ThrowMine.canceled -= instance.OnThrowMine;
            @Pause.started -= instance.OnPause;
            @Pause.performed -= instance.OnPause;
            @Pause.canceled -= instance.OnPause;
            @Dash.started -= instance.OnDash;
            @Dash.performed -= instance.OnDash;
            @Dash.canceled -= instance.OnDash;
            @DebugAIChangeState.started -= instance.OnDebugAIChangeState;
            @DebugAIChangeState.performed -= instance.OnDebugAIChangeState;
            @DebugAIChangeState.canceled -= instance.OnDebugAIChangeState;
            @DebugAIResetPosition.started -= instance.OnDebugAIResetPosition;
            @DebugAIResetPosition.performed -= instance.OnDebugAIResetPosition;
            @DebugAIResetPosition.canceled -= instance.OnDebugAIResetPosition;
            @DebugRemoveUltimateAbilityCooldown.started -= instance.OnDebugRemoveUltimateAbilityCooldown;
            @DebugRemoveUltimateAbilityCooldown.performed -= instance.OnDebugRemoveUltimateAbilityCooldown;
            @DebugRemoveUltimateAbilityCooldown.canceled -= instance.OnDebugRemoveUltimateAbilityCooldown;
        }

        public void RemoveCallbacks(IPlayerInputActionsActions instance)
        {
            if (m_Wrapper.m_PlayerInputActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerInputActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerInputActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerInputActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerInputActionsActions @PlayerInputActions => new PlayerInputActionsActions(this);

    // MenuInputActions
    private readonly InputActionMap m_MenuInputActions;
    private List<IMenuInputActionsActions> m_MenuInputActionsActionsCallbackInterfaces = new List<IMenuInputActionsActions>();
    private readonly InputAction m_MenuInputActions_GoBack;
    private readonly InputAction m_MenuInputActions_LeftDirection;
    private readonly InputAction m_MenuInputActions_RightDirection;
    private readonly InputAction m_MenuInputActions_UpDirection;
    private readonly InputAction m_MenuInputActions_DownDirection;
    private readonly InputAction m_MenuInputActions_LeftCharacter;
    private readonly InputAction m_MenuInputActions_RightCharacter;
    private readonly InputAction m_MenuInputActions_LeftSkin;
    private readonly InputAction m_MenuInputActions_RightSkin;
    private readonly InputAction m_MenuInputActions_StartGame;
    private readonly InputAction m_MenuInputActions_DebugUnlockSkins;
    public struct MenuInputActionsActions
    {
        private @PlayerInputAction m_Wrapper;
        public MenuInputActionsActions(@PlayerInputAction wrapper) { m_Wrapper = wrapper; }
        public InputAction @GoBack => m_Wrapper.m_MenuInputActions_GoBack;
        public InputAction @LeftDirection => m_Wrapper.m_MenuInputActions_LeftDirection;
        public InputAction @RightDirection => m_Wrapper.m_MenuInputActions_RightDirection;
        public InputAction @UpDirection => m_Wrapper.m_MenuInputActions_UpDirection;
        public InputAction @DownDirection => m_Wrapper.m_MenuInputActions_DownDirection;
        public InputAction @LeftCharacter => m_Wrapper.m_MenuInputActions_LeftCharacter;
        public InputAction @RightCharacter => m_Wrapper.m_MenuInputActions_RightCharacter;
        public InputAction @LeftSkin => m_Wrapper.m_MenuInputActions_LeftSkin;
        public InputAction @RightSkin => m_Wrapper.m_MenuInputActions_RightSkin;
        public InputAction @StartGame => m_Wrapper.m_MenuInputActions_StartGame;
        public InputAction @DebugUnlockSkins => m_Wrapper.m_MenuInputActions_DebugUnlockSkins;
        public InputActionMap Get() { return m_Wrapper.m_MenuInputActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuInputActionsActions set) { return set.Get(); }
        public void AddCallbacks(IMenuInputActionsActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuInputActionsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuInputActionsActionsCallbackInterfaces.Add(instance);
            @GoBack.started += instance.OnGoBack;
            @GoBack.performed += instance.OnGoBack;
            @GoBack.canceled += instance.OnGoBack;
            @LeftDirection.started += instance.OnLeftDirection;
            @LeftDirection.performed += instance.OnLeftDirection;
            @LeftDirection.canceled += instance.OnLeftDirection;
            @RightDirection.started += instance.OnRightDirection;
            @RightDirection.performed += instance.OnRightDirection;
            @RightDirection.canceled += instance.OnRightDirection;
            @UpDirection.started += instance.OnUpDirection;
            @UpDirection.performed += instance.OnUpDirection;
            @UpDirection.canceled += instance.OnUpDirection;
            @DownDirection.started += instance.OnDownDirection;
            @DownDirection.performed += instance.OnDownDirection;
            @DownDirection.canceled += instance.OnDownDirection;
            @LeftCharacter.started += instance.OnLeftCharacter;
            @LeftCharacter.performed += instance.OnLeftCharacter;
            @LeftCharacter.canceled += instance.OnLeftCharacter;
            @RightCharacter.started += instance.OnRightCharacter;
            @RightCharacter.performed += instance.OnRightCharacter;
            @RightCharacter.canceled += instance.OnRightCharacter;
            @LeftSkin.started += instance.OnLeftSkin;
            @LeftSkin.performed += instance.OnLeftSkin;
            @LeftSkin.canceled += instance.OnLeftSkin;
            @RightSkin.started += instance.OnRightSkin;
            @RightSkin.performed += instance.OnRightSkin;
            @RightSkin.canceled += instance.OnRightSkin;
            @StartGame.started += instance.OnStartGame;
            @StartGame.performed += instance.OnStartGame;
            @StartGame.canceled += instance.OnStartGame;
            @DebugUnlockSkins.started += instance.OnDebugUnlockSkins;
            @DebugUnlockSkins.performed += instance.OnDebugUnlockSkins;
            @DebugUnlockSkins.canceled += instance.OnDebugUnlockSkins;
        }

        private void UnregisterCallbacks(IMenuInputActionsActions instance)
        {
            @GoBack.started -= instance.OnGoBack;
            @GoBack.performed -= instance.OnGoBack;
            @GoBack.canceled -= instance.OnGoBack;
            @LeftDirection.started -= instance.OnLeftDirection;
            @LeftDirection.performed -= instance.OnLeftDirection;
            @LeftDirection.canceled -= instance.OnLeftDirection;
            @RightDirection.started -= instance.OnRightDirection;
            @RightDirection.performed -= instance.OnRightDirection;
            @RightDirection.canceled -= instance.OnRightDirection;
            @UpDirection.started -= instance.OnUpDirection;
            @UpDirection.performed -= instance.OnUpDirection;
            @UpDirection.canceled -= instance.OnUpDirection;
            @DownDirection.started -= instance.OnDownDirection;
            @DownDirection.performed -= instance.OnDownDirection;
            @DownDirection.canceled -= instance.OnDownDirection;
            @LeftCharacter.started -= instance.OnLeftCharacter;
            @LeftCharacter.performed -= instance.OnLeftCharacter;
            @LeftCharacter.canceled -= instance.OnLeftCharacter;
            @RightCharacter.started -= instance.OnRightCharacter;
            @RightCharacter.performed -= instance.OnRightCharacter;
            @RightCharacter.canceled -= instance.OnRightCharacter;
            @LeftSkin.started -= instance.OnLeftSkin;
            @LeftSkin.performed -= instance.OnLeftSkin;
            @LeftSkin.canceled -= instance.OnLeftSkin;
            @RightSkin.started -= instance.OnRightSkin;
            @RightSkin.performed -= instance.OnRightSkin;
            @RightSkin.canceled -= instance.OnRightSkin;
            @StartGame.started -= instance.OnStartGame;
            @StartGame.performed -= instance.OnStartGame;
            @StartGame.canceled -= instance.OnStartGame;
            @DebugUnlockSkins.started -= instance.OnDebugUnlockSkins;
            @DebugUnlockSkins.performed -= instance.OnDebugUnlockSkins;
            @DebugUnlockSkins.canceled -= instance.OnDebugUnlockSkins;
        }

        public void RemoveCallbacks(IMenuInputActionsActions instance)
        {
            if (m_Wrapper.m_MenuInputActionsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuInputActionsActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuInputActionsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuInputActionsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuInputActionsActions @MenuInputActions => new MenuInputActionsActions(this);
    public interface IPlayerInputActionsActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnAccelerate(InputAction.CallbackContext context);
        void OnReverse(InputAction.CallbackContext context);
        void OnBrake(InputAction.CallbackContext context);
        void OnShootingMode(InputAction.CallbackContext context);
        void OnCameraMove(InputAction.CallbackContext context);
        void OnCameraMoveMouse(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnSpecialAbility(InputAction.CallbackContext context);
        void OnResetCamera(InputAction.CallbackContext context);
        void OnThrowMine(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
        void OnDash(InputAction.CallbackContext context);
        void OnDebugAIChangeState(InputAction.CallbackContext context);
        void OnDebugAIResetPosition(InputAction.CallbackContext context);
        void OnDebugRemoveUltimateAbilityCooldown(InputAction.CallbackContext context);
    }
    public interface IMenuInputActionsActions
    {
        void OnGoBack(InputAction.CallbackContext context);
        void OnLeftDirection(InputAction.CallbackContext context);
        void OnRightDirection(InputAction.CallbackContext context);
        void OnUpDirection(InputAction.CallbackContext context);
        void OnDownDirection(InputAction.CallbackContext context);
        void OnLeftCharacter(InputAction.CallbackContext context);
        void OnRightCharacter(InputAction.CallbackContext context);
        void OnLeftSkin(InputAction.CallbackContext context);
        void OnRightSkin(InputAction.CallbackContext context);
        void OnStartGame(InputAction.CallbackContext context);
        void OnDebugUnlockSkins(InputAction.CallbackContext context);
    }
}
